project-ncl/repour

repour/asgit.py, repour/scm/git_provider.py
Currently repour reports `git push` failures with exit code 1. This exit
code is interpreted by Maitai as a SYSTEM_ERROR. We want to change this
to a 'build error' instead by returning exit code 10 instead (See NCL-2079)
This commit modifies the exit_code of the git push exception (if any) to
10, and improves the description error by telling the user it does not
have the required permissions to push.
=> [NCL-2871] Don't report missing permissions as err

repour/server/endpoint/endpoint.py
Repour logs when a callback fails to be completed is outputing the full
stacktrace. This is annoying since it doesn't provide that much
information, we just really need to know the reason of the failed
callback.
This commit removes the full stacktrace and instead just prints the
reason of the failed callback. In my opinion, this will help increase
the readability of the logs.
See the JIRA for the full stacktrace.
=> [NCL-2896] Dont shw stacktrace for failed callback

repour/main.py
Format is:
<yyyy-mm-dd> HH:mm:ss,SSS [Log level] Extra logs
=> [PNC-1.0.x] [NCL-2956] Make logs for pnc use same format

repour/asgit.py, repour/scm/git_provider.py
The original intention of creating tags and branches for a commit on
'/adjust' was to use tags for everything, and possibly do manual changes
to the branch if we require so.
However, we think that the creation of branches is unecessary since we
don't really use it, and if we have to, we can manually create the
branch from the tag
=> [NCL-2948] Dont' create branches on /adjust

repour/scm/git_provider.py
Because we do not create branches anymore for /adjust, I had to change
the git push command to:
```
git push --tags
```
Sometimes this command will fail if the tag already exists on the remote
server (this situation happens because we do a shallow clone, and that
clone doesn't have all the tags in the remote server). This is fine
because that means that the tag that already exists will have the same
content as the tag created locally. So it's ok that the push failed.
=> git push fails because tag already exists, is fine

README.asciidoc, repour/logs/file_callback_log.py, repour/logs/websocket_log.py, repour/main.py, repour/server/endpoint/endpoint.py, repour/server/endpoint/ws.py, repour/server/server.py, repour/websockets.py
The live logs will only work when the operation is done in callback
mode. In callback mode, the callback id is sent to the requestor. The
requestor can then use that callback id to connect to a websocket
endpoint and receive live logs.
The websocket endpoint is:
```
ws://<server>:<port>/callback/{callback_id}
```
This is achieved by adding a logger handler that receives the logs, and
sends them to the websocket clients.
There is another logger handler used to capture the logs for specific
callback ids and save them into individual files. The aim is to be able
to forward to the requestor the relevant logs for that particular callback
id, beyond using websockets.
There is also a function that is activated. Its goal is to cleanup the
closed websockets that repour is sending logs if the …
=> [NCL-2882] Send live logs of repour operations

repour/main.py, repour/server/endpoint/endpoint.py, repour/server/server.py
This commit requires the user to define an Environment variable named
'REPOUR_URL'. The value of that variable will be the external url of
repour, for e.g 'repour.somewhere.in.the.cloud'
The websocket link is only sent when callback mode is used.
The callback reply will look like:
```
{
"callback": {
"id": "fancy-id",
"websocket": "ws://pnc-repour.instance.magic/callback/fancy-id"
}
}
```
=> [NCL-2882] Send back websocket link to requestor

repour/adjust/adjust.py
Currently for the `/adjust` endpoint, if hte ref is a hash, `/adjust` doesn't work. This commit fixes it.
=> [NCL-3005] Adjust from internal hash

repour/adjust/adjust.py, repour/asutil.py, repour/clone.py, repour/config/default-config.json, repour/pull.py
The Git url that we receive from the request might not have the username
in it anymore. This makes sense because Repour is configured to clone
repositories from a specific user, as repour is running with the private
keys of that specific user.
As such, the username of the git url we receive is _always_ for that
specific user. So it makes sense to just omit the username in the git
url we receive, and let repour add it implicitly instead. In that way,
if the specific user repour uses has to change, we only have to do the
change in repour, and not in the various clients of repour.
=> [NCL-3041] Update to handle scm user on its own

repour/asgit.py, repour/asutil.py, repour/config/default-config.json, test/test_adjust.py, test/test_asgit.py, test/test_integration.py, test/test_pull.py, test/test_validation.py, test/util.py
The repour tests haven't been updated with all the changes that have happened in the repour codebase.
This PR attempts to fix all the existing tests to make them pass.
Most of the changes concern changes in moving of code, removal of creation of branches, and some minor changes in the way a function has to be called.
=> Fix failing tests

test/__main__.py, test/test_adjust.py, test/test_asgit.py, test/test_pull.py, test/util.py
We don't want to use 'git -C' because that configuration is not
available in the Git version we are using on RHEL 7 / CentOS 7
=> Don't use 'git -C' option for tests

README.asciidoc, repour/cloneadjust.py, repour/scm/git_provider.py, repour/server/endpoint/validation.py, repour/server/server.py
This endpoint allows a user to sync and optionally run PME on the
output.
If the ref is a branch, the branch will be pushed to the target repo. If
the ref is a tag, the tag will be pushed to the target repo. If the ref
is a SHA, a branch will be created and named 'branch-<ref>' and pushed
to the target repo. The latter is required to get a particular commit to
the target repository.
The adjust parameter, when enabled, will run PME, and the result is put
inside the response in key 'adjust_result'. The content of
'adjust_result' is exactly the same as the output for the '/adjust'
endpoint.
=> [NCL-2981] Add endpoint /cloneadjust

repour/adjust/adjust.py, repour/scm/git_provider.py, repour/server/endpoint/validation.py
That sync feature is only enabled if the keys:
- originRepoUrl *and*
- sync (with value True)
are sent to the `/adjust` endpoint. Otherwise the sync won't happen and
`/adjust` will behave as before.
While I did a similar commit with adding the `/cloneadjust` endpoint, I
now realize that using the `/cloneadjust` endpoint on the Maitai process
is awkward because, based on the 'sync' being true or false, I'd have to
call `/cloneadjst` or `/adjust` endpoint respectively on the Maitai
side.
I believe it's better to add the feature to the `/adjust` endpoint so
that it requires minimum changes on the Maitai side, while keeping
`/adjust` backwards compatible.
A future commit will remove the `/cloneadjust` endpoint.
=> [NCL-2981] Adapt /adjust to have syncing feature

repour/adjust/adjust.py, repour/clone.py, repour/scm/git_provider.py
The previous behaviour of `/clone` was to create a branch if the ref
wasn't a branch. The original idea was to allow the user to manually
apply additional changes to the branch if required.
However, it turns out we never really needed that feature. This commit
removes this behaviour.
For both /clone and /adjust (with auto-sync enabled), if the ref is a:
- tag => tag gets synced with internal repo
- branch => branch gets synced with internal repo
- SHA => SHA gets synced with internal repo (via indirect creation of a
tag with format 'repour-sync-ref' to make this possible)
=> [NCL-3117] Unify syncing behaviour for /clone and /adjust

repour/adjust/pme_provider.py
The removed repositories are added to the current result so no change
to existing tooling handling the resulting object and passing it further
in the build púrocess rocess updates should be needed.
=> NCL-3020: Capture list of remote repositories removed by PME

repour/clone.py, repour/scm/git_provider.py, repour/server/endpoint/validation.py
This applies to the `/clone` endpoint. If the `ref` is not specified,
the default behaviour is to clone the origin url to the target url
Inspired from: https://stackoverflow.com/a/7216269/2907906
=> [NCL-3071] Allow syncing all the repository

repour/adjust/pme_provider.py
Now it checks if the file exists, because when no repos are removed the
file doesn't get created.
=> NCL-3221 - Can't capture the removed repository file

repour/adjust/adjust.py, repour/asgit.py, repour/pull.py, repour/scm/git_provider.py, test/test_asgit.py, test/test_pull.py, test/util.py
Before, we used a fixed date for all of the commits that repour did.
This was done to generate the same commit SHA if a previous commit
containing the same repository directory contents existed.
This was done so that we don't create *new* commits every time repour
runs the adjust phase, if the same changes are applied to the source
repository as before.
(The commit SHA is built from the tree SHA, parent commit SHA, date,
author, commit message etc. We tried to keep the parent commit SHA,
date, author, commit message constant in Repour)
By focusing on the tree SHA instead of the commit SHA, we are now able
to use the real date in our commits, while preventing duplication of
commits for each adjust phase which produces the same changes.
This commit attempts to use a different approach: …
=> [NCL-2889] Use correct time in repour commits

repour/adjust/adjust.py, repour/adjust/pme_provider.py, repour/config/default-config.json, repour/server/endpoint/validation.py
The `/adjust` endpoint is adjust to now also accept the parameters:
- tempBuild [optional] (with as value a boolean)
- tempBuildTimestamp [optional] (with as value a string)
For `tempBuildTimestamp` to have any effect, `tempBuild` key must be
specified and must have a value of 'true'.
If `tempBuild` is set to true, PME will use a specific Indy group for
PME alignmnent.
The new parameter to define in the repour config is:
```
{
...
"temp_build_indy_group": "<indy group to use>",
...
}
```
This commit allows further work to be done on the Maitai side. When the
specifics on how PME will deal with temp build and temp build timestamp
is known, a further commit will be done to use the new parameters.
=> [NCL-3503] endpoint adjusted to accept new param

repour/adjust/adjust.py
If the timestamp key has no value, we should use the keyword
'temporary'. Unfortunately we took some wrong assumptions and the
keyword got set to 'null'. This commit fixes this.
=> [NCL-3502] Fix bug where timestamp not added

repour/server/endpoint/cancel.py, repour/server/endpoint/endpoint.py, repour/server/endpoint/validation.py, repour/server/server.py
The way to use cancel operation is by using the endpoint:
```
POST /cancel/{task_id}
```
The task id is specified from the original request, and is only
supported for the `/adjust` endpoint for now.
The request should send:
```
POST /adjust
{
...
"taskId": "1234"
}
```
=> [NCL-2467] Add cancel support

repour/adjust/pme_provider.py
There are some git repositories where the root pom.xml is not located in
the root location of the repository, but rather in a folder.
```
<folder>/pom.xml
```
PME allows you to specify the `--file=<folder>/pom.xml` param to be
able to run PME from the root of the git repository.
However, when PME is finished, repour tries to read the file
`target/pom-manip-ext-result.json` from the root git repository, instead
of from `<folder>/target/pom-manip-ext-result.json`
So we can fix this issue by either:
- change directory to the 'folder' in the '--file' param, and remove
the '--file' param in the list of PME parameters. Then run PME from
the 'folder' to replicate what we do
- Not remove the '--file' param in hte list of PME parameters, and use
the 'folder' to properly grab the …
=> [NCL-3601][master] Correctly process non top-level pom.xml

repour/adjust/pme_provider.py
There are some git repositories where the root pom.xml is not located in
the root location of the repository, but rather in a folder.
```
<folder>/pom.xml
```
PME allows you to specify the `--file=<folder>/pom.xml` param to be
able to run PME from the root of the git repository.
However, when PME is finished, repour tries to read the file
`target/pom-manip-ext-result.json` from the root git repository, instead
of from `<folder>/target/pom-manip-ext-result.json`
So we can fix this issue by either:
- change directory to the 'folder' in the '--file' param, and remove
the '--file' param in the list of PME parameters. Then run PME from
the 'folder' to replicate what we do
- Not remove the '--file' param in hte list of PME parameters, and use
the 'folder' to properly grab the …
=> [NCL-3601][v-1.2] Correctly process non top-level pom.xml

repour/adjust/pme_provider.py
There are some git repositories where the root pom.xml is not located in
the root location of the repository, but rather in a folder.
```
<folder>/pom.xml
```
PME allows you to specify the `--file=<folder>/pom.xml` param to be
able to run PME from the root of the git repository.
However, when PME is finished, repour tries to read the file
`target/pom-manip-ext-result.json` from the root git repository, instead
of from `<folder>/target/pom-manip-ext-result.json`
So we can fix this issue by either:
- change directory to the 'folder' in the '--file' param, and remove
the '--file' param in the list of PME parameters. Then run PME from
the 'folder' to replicate what we do
- Not remove the '--file' param in hte list of PME parameters, and use
the 'folder' to properly grab the …
=> [NCL-3601][v1.1] Correctly process non top-level pom.xml

.gitignore, RELEASE_INSTRUCTIONS.md, repour/__init__.py, repour/auth/auth.py, repour/server/endpoint/info.py, repour/server/server.py
This PR adds support for an informational endpoint in Repour when accessing repour on '/'.
To do so, I deactivated the authentication on the '/' endpoint only so that anyone could access it.
The informational endpoint shows the Repour version (as defined in `repour/__init__.py`) and the Git SHA, if the `.git` folder is in the root folder of the application.
Instructions on what to update during a release is also now provided.
=> [NCL-2167] Add informational endpoint in Repour

repour/asgit.py
If the tag name after the adjust alignment already exists in the
external repo (with pre-sync enabled), we still cannot be sure that the
tag is present in the internal repository, since we only push the tag we
originally want to sync.
This commit makes sure that we also push into the internal repo the tag
which contains the alignment changes, just in case.
Thanks to @jochrist for reporting this bug!
=> Push existing tag name for /adjust

repour/adjust/adjust.py, repour/scm/git_provider.py
This is required to know if:
- existing tag with same contents already exists in target repository if
repo sync is on
- if existing tag with name <version> exists, push new tag with name
<version>-<sha>
=> [v1.3][NCL-3980] Sync target repo tags when running /adjust

repour/adjust/adjust.py, repour/scm/git_provider.py
This is required to know if:
- existing tag with same contents already exists in target repository if
repo sync is on
- if existing tag with name <version> exists, push new tag with name
<version>-<sha>
=> [NCL-3980] Sync target repo tags when running /adjust

repour/adjust/adjust.py, repour/clone.py, repour/scm/git_provider.py
On a fresh clone, sometimes we still get 'diffs' in the working tree
because of weird behavious between CRLF and LF file ending conversion
between windows and linux, and the .gitattributes file.
This prevents us from checking out the branch/tag we want. So by using
the '-f' option in checkout, this allows us change branch/tag and
discard the local changes.
See: https://help.github.com/articles/dealing-with-line-endings/
=> [v1.3][NCL-3984] Use checkout -f when changing branch

repour/adjust/adjust.py, repour/clone.py, repour/scm/git_provider.py
On a fresh clone, sometimes we still get 'diffs' in the working tree
because of weird behavious between CRLF and LF file ending conversion
between windows and linux, and the .gitattributes file.
This prevents us from checking out the branch/tag we want. So by using
the '-f' option in checkout, this allows us change branch/tag and
discard the local changes.
See: https://help.github.com/articles/dealing-with-line-endings/
=> [NCL-3984] Use checkout -f when changing branch

repour/scm/git_provider.py
When cloning a private github repositories, the user should add a
particular github user so that Repour has permissions to do it. The
error message will tell the user what to do when such a case happens.
The particular github user is specified in the environment variable
'PRIVATE_GITHUB_USER'
=> [NCL-4047] Err msg for github private repo perm

CHANGELOG.md, repour/adjust/adjust.py, repour/scm/git_provider.py
The case is when the sync is on, and the downstream repository has the
ref but not the upstream repository. In that case we shouldn't fail and
go as before.
Before it was failing because it was trying to checkout the ref from the
upstream repository.
=> [NCL-4069] Handle case with adjust and pre-sync on

CHANGELOG.md, repour/auth/auth.py, repour/config/default-config.json, repour/scm/git_provider.py, repour/server/endpoint/external_to_internal.py, repour/server/endpoint/validation.py, repour/server/server.py
Description of endpoint
=======================
Endpoint is: /git-external-to-internal
The endpoint is not authenticated. Therefore any user can access it.
Request
--------
POST /git-external-to-internal
```
{"external_url": "<url>"}
```
Responses
--------
- Success!
HTTP status: 200
```
{
"external_url": "<url>",
"internal_url": "<internal-url>",
"log": "<logs>"
}
```
- Failure
HTTP status: 500
```
{
"error_traceback": "<error-traceback>",
"error_type": "<error-type>",
"log": "<logs>"
}
```
Configuration Changes
=====================
We need to add key 'git_url_internal_template' to the configuration.
This is used as the first part of the internal url.
e.g 'git_url_internal_template': 'git+ssh://<private-git-server>/gerrit/'
=>  [NCL-4082] Endpoint to translate external scm to internal 

repour/scm/git_provider.py
In older git versions, git fetch --tags does not fetch the branches.
Sad.
=> Use git-fetch before using is-branch check

venv/container.txt
Multidict 4.4.1 requires Python >= 3.5, and right now we only use Python
3.4.
Fix multidict version to 4.4.0 to make it work on Python 3.4
=> Fix multidict to 4.4.0

repour/clone.py
In a previous commit, we were checking if a tag already exists.
Unfortunately we were using the wrong variable (ref) to compare the tag.
We should use the variable 'tag_name' instead
=> Bugfix: check correct variable that contains tag information

CHANGELOG.md, repour/asgit.py, repour/config/default-config.json
During testing of repour, we use the `/adjust` endpoint with sync on between the
official internal git repository (which we consider as the external
repo) and a test internal git repository. There is a particular case
when the syncing is problematic:
- test internal git repository is aligned from upstream tag 1.0.0 and repour
creates tag 1.0.0-company-1
- some time later the official git repository is aligned from upstream
tag 1.0.0 in official repour instance and creates tag 1.0.0-company-1
Then the next time we sync the official internal git repo to the test
internal git repository, it fails because we have the same tag
(1.0.0-company-1) pointing to different commitids! (alignment will be
done slightly differently between the test repour and production repour
instance)
So instead this …
=> [NCL-4120] Repour append commit id to tag on devel mode

repour/adjust/adjust.py, repour/clone.py, repour/scm/git_provider.py
When syncing branches on the `/adjust` endpoint, we:
1. git clone the upstream repository and checkout the ref
2. remove the remote 'origin' and set remote 'origin' to the internal repository
3. push and sync the 'ref' to sync to internal repository
4. Run PME
5. Create a commit, tag and push to internal repository
The issue is that on step 2, removing the remote 'origin' affects step 3.
Step 3 tries to identify if the ref to sync is a branch or a tag or a
sha. The reasoning is that if it's a branch or a tag, we push them as-is
to the internal repository. If it's a sha, we need to push it as a tag
to the internal repository.
On Step 3, we assume by default that the branch to check is
'remotes/origin/<ref>'. Unfortunately since we removed the remote
'origin' on Step 2, step 3 thinks the …
=> [NC-4231] Fix bug in repour syncing of branches

CHANGELOG.md, repour/adjust/adjust.py, repour/clone.py, repour/scm/git_provider.py
When syncing branches on the `/adjust` endpoint, we:
1. git clone the upstream repository and checkout the ref
2. remove the remote 'origin' and set remote 'origin' to the internal repository
3. push and sync the 'ref' to sync to internal repository
4. Run PME
5. Create a commit, tag and push to internal repository
The issue is that on step 2, removing the remote 'origin' affects step 3.
Step 3 tries to identify if the ref to sync is a branch or a tag or a
sha. The reasoning is that if it's a branch or a tag, we push them as-is
to the internal repository. If it's a sha, we need to push it as a tag
to the internal repository.
On Step 3, we assume by default that the branch to check is
'remotes/origin/<ref>'. Unfortunately since we removed the remote
'origin' on Step 2, step 3 thinks the …
=> [v1.4][NC-4231] Fix bug in repour syncing of branches

repour/adjust/adjust.py
user error is defined as an exit code less than 100
=> [NCL-4285] If ref not found, it should be a user error

CHANGELOG.md, repour/adjust/adjust.py
user error is defined as an exit code less than 100
=> [v1.4][NCL-4285] If ref not found, it should be a user error

repour/asgit.py, repour/scm/git_provider.py
We do provide the tag name as a result for the `/adjust` endpoint. But
we should also provide the commit id
=> [NCL-4650] Provide commit id on /adjust

ADJUST_PROVIDERS.rst, repour/adjust/adjust.py, repour/adjust/gradle_provider.py
This makes use of the init file provided by the plugin.
It is expected that this file is provided and a path to it
is specified as `gradleAnalyzerPluginInitFilePath`.
=> [NCL-4768] Adjustments in Repour after Gradle analyzer plugin release

repour/adjust/adjust.py
Fix in 1ba2534f4227f23246a5855592108a82114e818d was lacking update to the
adjust.py. This commit repairs it.
=> Fix returning of version in Gradle provider

repour/adjust/gradle_provider.py, repour/adjust/pme_provider.py, repour/adjust/util.py
This reuses the `CUSTOM_PME_PARAMETERS` variable and is subject
for refactoring after 1.7 release.
=> [NCL-4810] Add support for custom parameters for Gradle builds

repour/adjust/gradle_provider.py, repour/adjust/pme_provider.py, repour/adjust/util.py
This reuses the `CUSTOM_PME_PARAMETERS` variable and is subject
for refactoring after 1.7 release.
=> [NCL-4810] Add support for custom parameters for Gradle builds - 1.7

repour/adjust/util.py, test/test_adjust_utils.py
This is done by using argparse to parse the versions.
Cases tested:
```
-f <file>
--file=<file>
--file <file>
```
=> [v1.7][NCL-5064] Handle more cases to parse params from PME

repour/adjust/util.py, test/test_adjust_utils.py
This is done by using argparse to parse the versions.
Cases tested:
```
-f <file>
--file=<file>
--file <file>
```
=> [NCL-5064] Handle more cases to parse params from PME

README.asciidoc, repour/adjust/adjust.py, repour/clone.py, repour/server/endpoint/cancel.py, repour/server/endpoint/endpoint.py, repour/server/endpoint/external_to_internal.py, repour/server/endpoint/info.py, repour/server/server.py, venv/container.txt, venv/runtime.txt
We currently monitor endpoints requests and error by using the
Prometheus client, exposing the metrics in the `/metrics` endpoint. We
can optionally export the data to Graphite if environment variable
`GRAPHITE_SERVER` and `GRAPHITE_KEY`` are defined. `GRAPHITE_KEY` is the
prefix for the data, and is usually set to the url of the server.
You can also override the default port for the Graphite server with
`GRAPHITE_PORT`
The metrics monitored are:
- time request of `/adjust`, `/clone`, `/cancel`,
`/external-to-internal`, `/`, and sending result to callback urls
* This covers latency and traffic
- errors:
* validation json error
* 400 response
* 500 response
* can't send response to callback
- CPU, memory, GC
* Covers saturation
=> [v1.7][NCL-4974] Add monitoring to Repour

repour/adjust/gradle_provider.py, test/test_gradle_provider.py
In some cases, the user would like to specify which JVM to use for
Gradle manipulation.
This can be done by passing:
```
-DRepour_Java=<JVM version>
```
in the extra parameters.
=> [v1.7][NCL-5158] Add support for user to specify JVM for gradle

repour/scm/git_provider.py
This arises when a file in the tree has the same name as a branch. This
causes git to be confused and fails. So we pass '--' to tell git to
trust itself and that we want to checkout the branch.
=> [v1.7][NCL-5173] Use -- on checkout to disambiguate

repour/scm/git_provider.py
This arises when a file in the tree has the same name as a branch. This
causes git to be confused and fails. So we pass '--' to tell git to
trust itself and that we want to checkout the branch.
Must be used with a recent version of Git (2.18.1)
=> [NCL-5173] Use -- on checkout to disambiguate

repour/adjust/process_provider.py
This helps with debugging in the future since we can just copy pasta the
command logged into our machine.
Thanks to @rnc for the suggestion!
=> [NCL-5225] Print the cmd to run for adjust

repour/adjust/process_provider.py
This helps with debugging in the future since we can just copy pasta the
command logged into our machine.
=> [v1.7][NCL-5225] Print the cmd to run for adjust

repour/adjust/gradle_provider.py
The env var contains the JDK specified by the user.
=> [v1.7] Pass the env var when getting the gradle version

README.asciidoc, repour/logs/file_callback_log.py, repour/main.py, venv/container.txt
This commit adds support for sending logs to a Kafka instance. It relies
on the Red Hat's 'kafka-logging-handler' library for its task.
To activate the handler, 3 environment variables need to be defined:
- REPOUR_KAFKA_SERVER (format <host>:<port>)
- REPOUR_KAFKA_TOPIC
- REPOUR_KAFKA_CAFILE (location of the ca file to talk to kafka)
=> [NCL-3579] Add kafka logging

README.asciidoc, repour/adjust/gradle_provider.py, repour/logs/file_callback_log.py, repour/main.py, venv/container.txt, venv/integration-test.txt, venv/runtime.txt
This commit adds support for sending logs to a Kafka instance. It relies
on the Red Hat's 'kafka-logging-handler' library for its task.
To activate the handler, 3 environment variables need to be defined:
- REPOUR_KAFKA_SERVER (format <host>:<port>)
- REPOUR_KAFKA_TOPIC
- REPOUR_KAFKA_CAFILE (location of the ca file to talk to kafka)
=> [v1.8][NCL-3579] Add kafka logging

repour/adjust/gradle_provider.py
The env var contains the JDK specified by the user.
=> Pass the env var when getting the gradle version

repour/adjust/pme_provider.py, repour/adjust/util.py, repour/main.py, repour/server/endpoint/endpoint.py
The headers are passed along to the callback server (Maitai), and to PME
for now.
GME and project-manipulator do not yet handle log contexts.
The format of the log-context passed to PME is currently:
```
--log-context=<key1>=<value1>,<key2>=<value2>
```
=>  [NCL-5067] Capture log-context headers, and pass along

repour/adjust/util.py
The delimiter is used to separate the key and value for the HTTP headers
=> [NCL-5098] Use ':' instead of '=' as delimiter

repour/main.py, repour/server/endpoint/endpoint.py
The loggerName is set to 'org.jboss.pnc._userlog_'
=> set loggerName so that bifrost processes repour data

repour/adjust/adjust.py, repour/asutil.py, test/test_asutil.py
A new configuration has to be added:
- adjust_authorized_url
=> [NCL-5090] Verify if the adjust params use non-authorized urls

repour/adjust/gradle_provider.py, repour/scm/git_provider.py
This avoid cases where the 'gradle' folder is added in the .gitignore,
and therefore the result of the alignment gets lost.
=> [v1.8][NCLSUP-62] Explicitly add file 'gradle/gme-repos.gradle'

repour/adjust/gradle_provider.py, repour/lib/scm/git.py
This avoid cases where the 'gradle' folder is added in the .gitignore,
and therefore the result of the alignment gets lost.
=> [NCLSUP-62] Explicitly add file 'gradle/gme-repos.gradle'

README.asciidoc, poetry.lock, pyproject.toml, repour/server/endpoint/internal_scm.py, repour/server/endpoint/validation.py, repour/server/server.py, test/test_internal_scm.py
The `/internal-scm` endpoint is used to create a new Gerrit repository.
The request is:
```
{
"project": nonempty_noblank_str,
"owner_groups": [nonempty_noblank_str],
Optional("description"): null_or_str,
Optional("parent_project"): null_or_str,
Optional("callback"): callback_raw,
}
```
And the response is:
```
{
"status": "SUCCESS_CREATED",
"readonly_url": "http://haha/project.git",
"readwrite_url": "git+ssh://haha/project.git",
}
{
"status": "SUCCESS_ALREADY_EXISTS",
"readonly_url": "http://haha/project.git",
"readwrite_url": "git+ssh://haha/project.git",
}
{
"error_traceback": "id",
"error_type": "error type",
"log": "everything went wrong"
}
```
The creation is done by mimicking what was done before in our Maitai
implementation. It is done by sshing into the Gerrit server and running …
=> [NCL-5414] Add internal-scm endpoint

repour/server/endpoint/validation.py
The `brewPullActive`, and the `tempBuild` flags will now be passed to
the alignment tools to determine what Indy group to talk to. We already
have the 'tempBuild' flag, so I'm just adding the `brewPullActive` one
for now.
The new `brewPullActive` flag is used to limit the usage of brew pull
and only be used as required. This is done to speed up builds.
The logic on how to use it for alignment will be done on another commit.
This commit is necessary so that we can work on the other bits (Maitai,
new Maitai, PNC) request DTOs.
=> [NCL-6165] Add brewPullActive to `adjust` request

repour/main.py
If the Kafka server is down, we don't really log and fail. This commit
just captures the failure and moves on to the next step
=> [NCLSUP-225] Just let kafka logging fail

repour/main.py
If the Kafka server is down, we don't really log and fail. This commit
just captures the failure and moves on to the next step
=> [v2.0][NCLSUP-225] Just let kafka logging fail

poetry.lock, pyproject.toml, repour/asutil.py, repour/lib/logs/file_callback_log.py
Changes done
------------
The first big change I did was on the logging department. I noticed that
we were printing very slowly (1 log line per ms) and investigated the
reason. The root cause is the file_callback_log.py logging handler,
which is used for websocket live logs (kinda deprecated with live log
now handled by Kafka), and to send back the full logs to the caller.
It stores the logs of a particular request into a file. The embarassing
issue is that we were creating/closing a new file handler everytime a
new log is emitted, which I learned is very costly and slow!
Instead we cache the file handler in an LRU cache. On eviction, the file
handler is closed. This change alone got rid of the log slowness.
The second improvement is that instead of reading the alignment log line
by line, …
=> [v2.0][NCLSUP-212] Improve logging of alignment

poetry.lock, pyproject.toml, repour/asutil.py, repour/lib/logs/file_callback_log.py
Changes done
------------
The first big change I did was on the logging department. I noticed that
we were printing very slowly (1 log line per ms) and investigated the
reason. The root cause is the file_callback_log.py logging handler,
which is used for websocket live logs (kinda deprecated with live log
now handled by Kafka), and to send back the full logs to the caller.
It stores the logs of a particular request into a file. The embarassing
issue is that we were creating/closing a new file handler everytime a
new log is emitted, which I learned is very costly and slow!
Instead we cache the file handler in an LRU cache. On eviction, the file
handler is closed. This change alone got rid of the log slowness.
The second improvement is that instead of reading the alignment log line
by line, …
=> [NCLSUP-212] Improve logging of alignment

pyproject.toml, repour/adjust/gradle_provider.py, repour/adjust/pme_provider.py, repour/adjust/process_provider.py, repour/adjust/project_manipulator_provider.py, test/test_pme_provider.py
PME 4.3 uses alignmentReport.json instead of manipulation.json
An upcoming version of GME (2.7?) will use alignmentReport.json instead
of manipulation.json also for reporting alignment results
=> [NCL-6553] Adapt to new file name for PME and GME

pyproject.toml, repour/adjust/gradle_provider.py, repour/adjust/pme_provider.py, test/test_pme_provider.py
PME 4.3 uses alignmentReport.json instead of manipulation.json
An upcoming version of GME (2.7?) will use alignmentReport.json instead
of manipulation.json also for reporting alignment results
also:
No need for verbose poetry install
Also I think this will help jenkins from not crashing because it's
getting confused with the fancy poetry output
=> [v2.0][NCL-6553] Adapt to new file name for PME and GME

repour/adjust/pme_provider.py, test/test_pme_provider.py
Before this commit, the aligned version would only be returned for PME
alignment if the artifactId / groupId were not overridden by the user.
This commit allows the aligned version to be set even when the
artifactId / groupId is overriden by the user
=> Set aligned version if present

repour/adjust/pme_provider.py, test/test_pme_provider.py
Before this commit, the aligned version would only be returned for PME
alignment if the artifactId / groupId were not overridden by the user.
This commit allows the aligned version to be set even when the
artifactId / groupId is overriden by the user
=> [v2] Set aligned version if present

repour/server/server.py
Repour by default prints access logs like this:
```
2021-05-13 20:08:40,056 [INFO] [NoContext] aiohttp.access:233 172.54.10.1 [13/May/2021:20:08:40 +0000] "GET /metrics HTTP/1.1" 200 11579 "-" "Prometheus/2.12.0"
2021-05-13 20:08:59,292 [INFO] [NoContext] aiohttp.access:233 172.54.104.1 [13/May/2021:20:08:59 +0000] "GET / HTTP/1.1" 200 374 "-" "kube-probe/1.11+"
2021-05-13 20:09:01,220 [INFO] [NoContext] aiohttp.access:233 172.54.6.1 [13/May/2021:20:09:01 +0000] "GET / HTTP/1.1" 200 355 "-" "okhttp/4.2.0"
```
This is pretty useless though and this shows up every minute. This
commit removes those access logs.
For requests done to endpoints doing "real work", the request as well as
the parameters are still printed.
=> Disable access log

repour/adjust/pme_provider.py, repour/adjust/project_manipulator_provider.py, repour/adjust/scala_provider.py, test/test_pme_provider.py, test/test_project_manipulator_provider.py, test/test_scala_manipulator.py
If a user enters a wrongly formatted alignment params (like unmatched
quotes), Repour fails to parse it and fails. That failure should be
marked as a User failed build rather than a system error.
=> [NCLSUP-435] Mark as user error when wrong input in alignment params

repour/adjust/pme_provider.py, repour/adjust/project_manipulator_provider.py, repour/adjust/scala_provider.py, test/test_pme_provider.py, test/test_project_manipulator_provider.py, test/test_scala_manipulator.py
If a user enters a wrongly formatted alignment params (like unmatched
quotes), Repour fails to parse it and fails. That failure should be
marked as a User failed build rather than a system error.
=> [2.1][NCLSUP-435] Mark as user error when wrong input in alignment params

README.asciidoc, repour/adjust/adjust.py, repour/lib/scm/git.py, test/test_git.py
If the ref to align is a merge-request (Gitlab, with format
'/merge-requests/<number>') or a pull-request (Github with format
'/pull/<number>'), with sync switched on, the merge-request is checkout
into a temporary branch, then the alignment tool is run, and the results
are added in a commit and pushed in a tag that starts with
'Pull_Request-'. The latter is done to not create any confusing that the
tag is from a merge-request.
With sync on for a merge-request, the checkout is not pushed into the
downstream repository in a branch, unlike for a regular ref. The commits
in the checkout are indirectly present via the 'Pull_Request-<tag>'
only.
=> [v2.1][NCLSUP-439] Support alignment from a merge-request

README.asciidoc, repour/adjust/adjust.py, repour/lib/scm/git.py, test/test_git.py
If the ref to align is a merge-request (Gitlab, with format
'/merge-requests/<number>') or a pull-request (Github with format
'/pull/<number>'), with sync switched on, the merge-request is checkout
into a temporary branch, then the alignment tool is run, and the results
are added in a commit and pushed in a tag that starts with
'Pull_Request-'. The latter is done to not create any confusing that the
tag is from a merge-request.
With sync on for a merge-request, the checkout is not pushed into the
downstream repository in a branch, unlike for a regular ref. The commits
in the checkout are indirectly present via the 'Pull_Request-<tag>'
only.
=> [NCLSUP-439] Support alignment from a merge-request

repour/lib/scm/git.py
Gerrit doesn't seem to support atomic pushes, so let's disable it by
default for now.
=> [NCLSUP-507] Switch tryAtomic to false

repour/lib/io/file_utils.py, repour/server/endpoint/endpoint.py, test/test_file_utils.py
Repour sends back the entire logs of an alignment in the callback.
However, we cannot send logs greater than a certain size because this
will cause OutOfMemory exceptions to the other services.
This commit:
- checks the size of the repour logs to send back no matter if the
alignment succeeded or failed
- if the size is greater than the maximum allowed (say foo bytes), then
we only return the last foo bytes of the repour logs since it's more
likely it'll contain the most important information
- mark the alignment as failed
The max size log can be configured in the `repour_config.json` as:
```
{
...
"max_log_size_bytes": 12345
}
```
If this setting is not specified, then we don't activate this feature**
=> [NCL-6882] Cut off logs after a certain size 

repour/adjust/gradle_provider.py, repour/adjust/pme_provider.py
We should only add versionSuffixAlternatives into the PME and GME CLI if
and only if:
- the temporary build has preferred persistent build alignment
- the suffix-prefix (minus the temporary string) is not empty (e.g for
managed services)
=> [NCL-7083] Only add versionSuffixAlternatives on some conditions

repour/adjust/pme_provider.py, repour/adjust/process_provider.py, repour/adjust/util.py, test/test_adjust_utils.py
Before this commit, Repour would remove the '-f' or '--file' option from
the extra PME parameters and run PME from the folder specified in the
'-f' option. However the PME '-f' option can be used to specify either a
folder or a file (can be named anything, doesn't have to finish with
pom.xml)
This logic unfortunately broke alignment for some projects where the
traditional file that contains the Maven setup is not named pom.xml.
This commit changes this by:
- truly providing the --file option values to PME rather than hiding it
- extracting any folder from the '--file' option to guess where the
results file will be generated
=> [NCLSUP-626] PME alignment: pass the --f option to PME directly

repour/main.py
Rename 'levelname' to 'level', rather than 'levelName'
=> [NCL-7150] Rename levelname to level

repour/lib/scm/git.py
Reverts project-ncl/repour#479 as build fails with "fatal: fetch --all does not take a repository argument"
=> Revert "[NCLSUP-750] Fetch tags with also '--all' option"

repour/main.py
Those errors are printed as ERROR when the kafka broker connection is broken.
```
ERROR [NoContext] <BrokerConnection node_id=2 host=<host> <connected> [IPv4 ('<ip>', 443)]>: socket disconnected
```
The broker eventually reconnects, so is more of an info or warning log. We don't want to have those logs printed as ERROR since they pollute our alerting emails. Therefore, this commit changes the log level for kafka to critical.
=> Hide kafka disconnect errors

repour/main.py
Those errors are printed as ERROR when the kafka broker connection is broken.
```
ERROR [NoContext] <BrokerConnection node_id=2 host=<host> <connected> [IPv4 ('<ip>', 443)]>: socket disconnected
```
The broker eventually reconnects, so is more of an info or warning log. We don't want to have those logs printed as ERROR since they pollute our alerting emails. Therefore, this commit changes the log level for kafka to critical.
=> [v2.4] Hide kafka disconnect errors

repour/asutil.py, repour/server/endpoint/endpoint.py
This is done because on Splunk, each error line is shown on the report page and it becomes really hard to follow what is going on. By just printing one big error log line (that may contain newlines), that should make the Repour error logs way more readable.
=> Print stderr in one error log line

repour/asutil.py, repour/server/endpoint/endpoint.py
This is done because on Splunk, each error line is shown on the report page and it becomes really hard to follow what is going on. By just printing one big error log line (that may contain newlines), that should make the Repour error logs way more readable.
=> [v2.4] Print stderr in one error log line

repour/adjust/adjust.py, repour/adjust/process_provider.py
Shlex is a python built-in lexer for unix-like shells that handles spaces in parameters and all escaping to avoid security issues.
If no escaping is required, shlex will leave the properties as is (functioning the same way as before). 
f.e. shlex.quote("-DrestMode=PERSISTENT") == "-DrestMode=PERSISTENT" would be true
f.e  with space, shlex.quote("-DrestDepenencyRanks=PRODUCT_ID : 123 and MILESTONE_ID") == "'-DrestDepenencyRanks=PRODUCT_ID : 123 and MILESTONE_ID'" would be true (shlex escaped the string with ' quotes)
Documentation:
https://docs.python.org/3.8/library/shlex.html#shlex.split
https://docs.python.org/3.8/library/shlex.html#shlex.join
https://docs.python.org/3.8/library/shlex.html#shlex.quote
=> handle intentional whitespace in quotes for defaultAlignmentParameters

repour/adjust/adjust.py
Replace it with 'is_ref_revision_internal'
This is to align with what Orch actually needs.
=> [NCL-6947] Replace 'is_ref_in_upstream_repo'

repour/adjust/adjust.py, repour/config/default-config.json
We do sometimes sync from one internal company repository to another internal company repository during alignment. In those cases, the ref should be considered internal no matter what.
To achieve this, we add a new configuration:
- `git_origin_repou_urls_internal` which contains a list of strings as values.
- the values are the urls of the repositories that should be considered internal to the company
=> [NCL-6947] Consider some origin urls as "internal"

repour/server/endpoint/endpoint.py, repour/server/endpoint/validation.py
All endpoints that accept callback should also support the 'taskId' field. It is a unique field that we can then use to 'cancel' the work in progress.
=> [NCL-8214] Add taskId to validation for all endpoints

repour/lib/scm/git.py
If during a sha check, it fails, we print a fatal error even though we shouldn't.
=> Hide wrong fatal error during sha check

repour/server/endpoint/endpoint.py
This is because the content is already sent to Bifrost, there's no need to send it again to BPM which might overwhelm it
=> [NCL-8814] Don't include stdout of error in callback

repour/adjust/adjust.py
This can be specified by the user in PNC via the generic parameters (currently only via bacon's build-config.yaml)
=> Allow user to override the value of adjust-delay-seconds

repour/server/endpoint/internal_scm_gitlab.py, test/test_internal_scm_gitlab.py
Gitlab has a particular regex format for group and project name. We need to modify the path we receive to adhere to that format.
Most of the paths we receive are from Github and Github probably has different naming requirements compared to Gitlab.
If the start or end of the group/project ends with a non-alpha-numeric character, we'll just replace it with an underscore.
=> [NCLSUP-1136] Sanitize project path for gitlab
