project-ncl/repour

repour/main.py

This is due to fixes in PME issue https://github.com/release-engineering/pom-manipulation-ext/issues/381

Ensure config file takes precedence over CLI

---

repour/adjust.py

- This will be refactored as a config. parameter.

Updated PME output file name.

---

Dockerfile
repour/adjust.py
repour/pull.py
repour/scm/git_provider.py

- Dumb http transport error with adjust.

Fix shallow clone error, start centralizing git utils.

---

repour/main.py

Format is:
<yyyy-mm-dd> HH:mm:ss,SSS [Log level] Extra logs

[NCL-2956] Make logs for pnc use same format

---

repour/server/endpoint/endpoint.py

The default maximum attempts on callback is 9, but repour tries 11
times. This commit fixes this by actually trying 9 times, not 11

[NCl-3290] Fix repour tries to max_attempts

---

repour/asgit.py

During the adjust phase, we'll use as tag name the version returned
after a PME run.
However there might be a scenario where the tag name we want to create
is already present. This commit attempts to detect that scenario, and
use as tag name '<original-tag-name>-<commit id of PME change>'
Also with this commit, we log if tag already exists or not

[NCL-3555] Add the commitid to tag if tag already exists

---

repour/scm/git_provider.py

Special thanks to @michalovjan for pointing out that the check wasn't doing a great job! :)

Improve branch check to check remote

---

repour/scm/git_provider.py

[Fix] KeyError, not keyError

---

repour/scm/git_provider.py

[v1.4][Fix] KeyError, not keyError

---

repour/adjust/adjust.py

We have to also handle temporary builds' settings.xml

[NCL-4248][v1.4] Provide correct settings.xml for alignment

---

CHANGELOG.md
repour/clone.py
repour/scm/git_provider.py

Sync everything on the `/clone` endpoint

[NCL-4255] Sync everything when internal repo new

---

CHANGELOG.md
repour/adjust/adjust.py
repour/adjust/project_manipulator_provider.py

Initial support for project-manipulator

---

repour/clone.py

[NCl-4231] typo bugfix

---

CHANGELOG.md
repour/adjust/pme_provider.py

[v1.4][NCL-4316] Use parent groupid/version when necessary for pom.xml with no PME disabled

---

repour/adjust/pme_provider.py

In Maven, we're allowed to not specify the project's groupId/version
since those values will be inherited from the parent groupId/version.
https://maven.apache.org/pom.html#Maven_Coordinates
This commit fixes the current implementation to use this.

[NCL-4316] Use parent groupid/version when necessary

---

repour/adjust/adjust.py
repour/scm/git_provider.py

Fetch tags from origin when syncing repos

---

CHANGELOG.md
repour/adjust/adjust.py
repour/adjust/noop_provider.py
repour/adjust/pme_provider.py
repour/adjust/process_provider.py
repour/adjust/project_manipulator_provider.py
repour/asgit.py
repour/asutil.py
repour/auth/auth.py
repour/auth/oauth2_jwt.py
repour/clone.py
repour/config/config.py
repour/exception.py
repour/repo.py
repour/scm/git_provider.py
repour/server/endpoint/cancel.py
repour/server/endpoint/endpoint.py
repour/server/endpoint/external_to_internal.py
repour/server/endpoint/info.py
repour/server/endpoint/ws.py
repour/server/server.py
repour/websockets.py
test/test_adjust.py
test/test_asutil.py
test/util.py
venv/container.txt
venv/runtime.txt

Python >= 3.5 support

---

repour/adjust/adjust.py
repour/adjust/pme_provider.py
repour/adjust/process_provider.py
repour/adjust/project_manipulator_provider.py

[NCl-3793] Add further support for Project-manipulator

---

repour/scm/git_provider.py

[NCL-4448] Missing git repo should be a user error

---

CHANGELOG.md
repour/scm/git_provider.py

[v1.4][NCL-4448] Missing git repo should be a user error

---

ADJUST_PROVIDERS.rst
CHANGELOG.md
repour/adjust/adjust.py
repour/adjust/gradle_provider.py
repour/adjust/process_provider.py

[NCL-4585] Add support for invoking Gradle analyze plugin

---

repour/main.py

[v1.6][NCL-4579] Log time in repour websocket log

---

ADJUST_PROVIDERS.rst
repour/adjust/adjust.py
repour/adjust/gradle_provider.py

This is a backported change from NCL-4585.

[NCL-4690] Add support for invoking Gradle analyze plugin

---

ADJUST_PROVIDERS.rst

Updated documentation to use currently required parameters.

Update the documentation for Gradle adjustments

---

test/test_adjust.py

[NCL-4690] Disable test_adjust.py for now

---

.github/PULL_REQUEST_TEMPLATE.md

Update PR template to use wiki

---

repour/adjust/gradle_provider.py

[v1.7] Use PME adjustResultData format for Gradle

---

repour/adjust/gradle_provider.py

[v1.7] Fix field in Gradle result json

---

repour/adjust/gradle_provider.py

Use PME adjustResultData format for Gradle

---

repour/adjust/gradle_provider.py

Instead we construct the path.

Do not use context manager for switching directories

---

repour/adjust/gradle_provider.py

Instead we construct the path.

Do not use context manager for switching directories - 1.7

---

ADJUST_PROVIDERS.rst
repour/adjust/gradle_provider.py
repour/adjust/pme_provider.py
repour/adjust/util.py

Code handling the backup file is now shared across PME and GME.

[NCL-4809] Add support for handling repositories-backup.xml

---

repour/adjust/project_manipulator_provider.py

Fix import shlex for project manipulator

---

repour/adjust/gradle_provider.py

Copy result data to adjust_result

---

repour/adjust/adjust.py
repour/adjust/gradle_provider.py
repour/adjust/pme_provider.py
repour/adjust/project_manipulator_provider.py
repour/adjust/util.py

Additionally made some refactoring to share the code across providers.

[NCL-4820] Support for temporary builds for Gradle

---

script/download-pme.sh

If no snapshot metadata is found, use the latest version

---

repour/adjust/gradle_provider.py

[v1.7][NCL-5057] Use system gradle if ./gradlew not present

---

repour/adjust/gradle_provider.py

[NCL-5057] Use system gradle if ./gradlew not present

---

repour/adjust/gradle_provider.py
test/test_gradle_provider.py

[v1.7][NCL-5057] Add test for gradle check

---

repour/adjust/gradle_provider.py
test/test_gradle_provider.py

[NCL-5057] Add tests

---

README.asciidoc
repour/adjust/adjust.py
repour/clone.py
repour/server/endpoint/cancel.py
repour/server/endpoint/endpoint.py
repour/server/endpoint/external_to_internal.py
repour/server/endpoint/info.py
repour/server/server.py
venv/container.txt

[NCL-4974] Add monitoring to repour

---

repour/adjust/pme_provider.py

NCL-4888 - Change EXECUTION_ROOT_NAME parameter name

---

repour/server/endpoint/endpoint.py

Special thanks to Andrea (@vibe13) for finding this bug!!!

[v1.7][NCL-4974] Increment correct counter for 400 error

---

repour/adjust/pme_provider.py

[NCL-5123] No need for await to parse pme results

---

repour/adjust/pme_provider.py

[NCL-5178] Repour should parse pom.xml with no namespace

---

repour/adjust/pme_provider.py

[v1.7][NCL-5178] Repour should parse pom.xml with no namespace

---

repour/adjust/gradle_provider.py
repour/adjust/process_provider.py

[NCL-5158] Use env to specify JAVA_HOME

---

repour/adjust/gradle_provider.py
repour/adjust/process_provider.py
test/test_gradle_provider.py

[NCL-5158] Allow user to specify Java to use for Gradle alignment

---

repour/adjust/gradle_provider.py

[v1.8][NCL-5224] Do not store the init gradle file in the repo

---

repour/adjust/gradle_provider.py

[NCL-5224] Do not store the init gradle file in the repo

---

repour/adjust/gradle_provider.py
repour/adjust/pme_provider.py
repour/adjust/util.py
test/test_gradle_provider.py
test/test_util.py

[v1.7] Specify java version for PME also

---

repour/adjust/gradle_provider.py
repour/adjust/pme_provider.py
repour/adjust/util.py
test/test_gradle_provider.py
test/test_util.py

Specify java version for PME also

---

repour/adjust/util.py

[v1.8][NCL-4866] Log removed repositories for PME

---

repour/adjust/util.py

[NCL-4866] Log removed repositories for PME

---

repour/adjust/gradle_provider.py
repour/adjust/pme_provider.py
repour/adjust/util.py

[NCL-5253] Print java version on alignment

---

repour/adjust/gradle_provider.py
repour/adjust/pme_provider.py
repour/adjust/util.py

[v1.8][NCL-5253] Print java version on align

---

repour/server/endpoint/validation.py
repour/server/server.py

Re-add some code removed from previous cleanup

---

repour/adjust/util.py
repour/main.py
repour/server/endpoint/endpoint.py

[NCL-5067] Add log-expires and log-tmp context

---

repour/main.py

This caused duplicate logs to appear everywhere. Woops

[v1.8] Remove duplicate call to configure logging

---

repour/adjust/gradle_provider.py

[v1.8] Make env var an empty dict if no Java defined

---

repour/adjust/gradle_provider.py

Make env var an empty dict if no Java defined

---

repour/main.py

Has to be in format:
```
"level": "DEBUG",
"mdc": {
"exp": "2019-11-25T15:29:01.580Z",
"processContext": "build-340",
"tmp": "true",
"requestContext": "3fec4443-986"
}
```

[NCL-3579] Reformat kafka output to be consistent with orch

---

repour/main.py

Make the values empty or exclude the field in the mdc, when there is no
value

[NCL-3579] Set mdc values to null if not present

---

script/download-pme.sh

Add md5 check when downloading PME

---

.gitignore
script/download-pme.sh

[v1.8] add md5 check for download pme

---

repour/adjust/adjust.py
repour/adjust/gradle_provider.py
test/test_gradle_provider.py

[v1.8][NCL-5333] Update repour for new GME CLI

---

repour/adjust/adjust.py
repour/adjust/gradle_provider.py
test/test_gradle_provider.py

[NCL-5333] Update repour for new GME CLI

---

repour/adjust/gradle_provider.py

[v1.8] Don't modify global default_parameters for gradle

---

repour/adjust/gradle_provider.py

Don't modify global default_parameters for gradle

---

repour/adjust/pme_provider.py

[NCL-5068] Adapt to new log context option for PME

---

script/download-pme.sh

[1.8][NCL-5393] Switch maven central url to https

---

script/download-pme.sh

[NCL-5393] Switch maven central url to https

---

script/download-pme.sh

[1.7][NCL-5393] Switch maven central url to https

---

repour/adjust/adjust.py
repour/logs/log_util.py
repour/main.py

[v1.8][NCL-5450] Add mdc logs for timings of alignment

---

repour/main.py

This is done to be consistent with the java kafka logging format

[NCL-5450] Add '@timestamp' key for kafka logging

---

repour/scm/git_provider.py

[v1.8][NCL-5488] Log error on git push with tags

---

repour/lib/scm/git.py

[NCL-5488] Log error on git push with tags

---

repour/asgit.py
repour/scm/git_provider.py

[v1.8][NCLSUP-10] Print more info on adjust / change branch

---

repour/asgit.py
repour/scm/git_provider.py

[v1.7][NCLSUP-10] Print more info on adjust / change branch

---

repour/lib/scm/asgit.py
repour/lib/scm/git.py

[NCLSUP-10] Print more info on adjust / change branch

---

repour/adjust/adjust.py
repour/adjust/gradle_provider.py

[v1.8][NCL-5652] Specify gradle path only if gradlew doesn't exist

---

repour/adjust/adjust.py
repour/adjust/gradle_provider.py

[NCL-5652] Specify gradle path only if gradlew doesn't exist

---

release.sh

Add initial script for release automation

---

release.sh

Chnage push from user input to parameter

---

poetry.lock
pyproject.toml
repour/server/endpoint/endpoint.py

[NCL-5762] Add HTTP header on callback for content-type

---

pyproject.toml
repour/__init__.py
repour/adjust/adjust.py
repour/clone.py
repour/lib/scm/asgit.py
repour/lib/scm/git.py

Special thanks to @rnc for his guidance on it!

[NCL-5839] Add git submodule support

---

repour/adjust/adjust.py
repour/server/endpoint/validation.py

[NCL-5884] Also consider new defaultAlignmentParams in adjust

---

repour/adjust/adjust.py
repour/server/endpoint/validation.py

[v2.0][NCL-5884] defaultAlignmentParams can be null / ""

---

repour/adjust/adjust.py
repour/server/endpoint/validation.py

[NCL-5884] defaultAlignmentParams can be null / ""

---

repour/adjust/project_manipulator_provider.py
repour/adjust/util.py

[NCL-5919] Add temporary builds processing for NPM versioning strategies

---

repour/adjust/project_manipulator_provider.py
repour/adjust/util.py

[2.0.x][NCL-5919] Add temporary builds processing for NPM versioning strategies

---

repour/adjust/project_manipulator_provider.py

[2.0][NCL-6009] Add missing import

---

repour/adjust/project_manipulator_provider.py

[NCL-6009] Add missing import

---

poetry.lock
pyproject.toml
repour/server/endpoint/validation.py
test/test_validation.py

[NCL-6038] add validation for git-scp urls

---

repour/adjust/gradle_provider.py
repour/adjust/util.py

[NCLSUP-138] Parse --target option for GME

---

repour/adjust/gradle_provider.py
repour/adjust/util.py

[2.0.x][NCLSUP-138] Parse --target option for GME

---

repour/server/endpoint/external_to_internal.py

[NCL-6089] Accept http as an acceptable scheme

---

repour/adjust/adjust.py
repour/adjust/gradle_provider.py
repour/adjust/pme_provider.py
repour/adjust/project_manipulator_provider.py
repour/adjust/util.py

[NCL-6168] Update Repour to not let users overwrite the constant params

---

repour/adjust/adjust.py
repour/adjust/gradle_provider.py
repour/adjust/pme_provider.py
repour/adjust/project_manipulator_provider.py
repour/adjust/util.py

[2.0.x][NCL-6168] Update Repour to not let users overwrite the constant manipulator params

---

repour/adjust/project_manipulator_provider.py

[2.0.x][NCL-6168] Project-manipulator: Fix repository group param name

---

repour/adjust/project_manipulator_provider.py

[NCL-6168] Project-manipulator: Fix repository group param name

---

poetry.lock
pyproject.toml
repour/server/endpoint/external_to_internal.py
repour/server/endpoint/validation.py
test/test_validation.py

Cherry Pick missing 2.0.1 commits

---

repour/adjust/gradle_provider.py

[Gradle] Don't fail if alignment disabled

---

repour/adjust/gradle_provider.py
repour/adjust/pme_provider.py
repour/adjust/util.py
test/test_util.py

[v2.0][NCLSUP-181] Fail if folder for alignment doesn't exist

---

repour/adjust/gradle_provider.py
repour/adjust/pme_provider.py
repour/adjust/util.py
test/test_util.py

[NCLSUP-181] Fail if folder for alignment doesn't exist

---

repour/adjust/adjust.py
repour/adjust/scala_provider.py

[NCL-6310][PART-1] add Scala/SBT support without alignment

---

repour/adjust/adjust.py
repour/adjust/gradle_provider.py
repour/adjust/pme_provider.py
repour/adjust/project_manipulator_provider.py
repour/adjust/scala_provider.py
repour/adjust/util.py

[NCL-6359] Add managedsvc suffix to service builds

---

repour/adjust/util.py

[NCL-6359] Fix reading of build category

---

repour/adjust/util.py

[NCL-6359] Enhance logging

---

repour/adjust/util.py

[NCL-6359] Fix key for adjustParameters

---

repour/adjust/util.py

[NCL-6359] Fix key for adjustParameters once again

---

repour/adjust/adjust.py

[NCL-6359] Fix validations for managedsvc persistent builds

---

repour/server/endpoint/external_to_internal.py
test/test_external_to_internal.py

[NCLSUP-268] Enable Scp-like urls to be created

---

repour/server/endpoint/external_to_internal.py

[NCLSUP-268] Improve external url validation

---

repour/adjust/process_provider.py

[NCL-6554] Return the process_provider data in Maven format

---

repour/adjust/pme_provider.py

[NCL-6553] generate alignmentReport.json if no alignment done

---

repour/adjust/gradle_provider.py

[NCL-6553] Adjust path of alignmentReport.json for gradle

---

repour/adjust/gradle_provider.py

[NCL-6553] Fix alignmentReport path again

---

repour/adjust/gradle_provider.py

[NCL-6553] Allow gradle alignment to finish even when disabled

---

repour/adjust/gradle_provider.py

[v2][NCL-6553] Allow gradle alignment to finish even when disabled

---

repour/adjust/gradle_provider.py

[NCL-6553] Add removed repositories

---

repour/adjust/gradle_provider.py

[v2][NCL-6553] Add removed repositories

---

repour/adjust/adjust.py
repour/adjust/gradle_provider.py
repour/adjust/pme_provider.py
repour/adjust/project_manipulator_provider.py
repour/adjust/scala_provider.py
repour/adjust/util.py
repour/config/default-config.json

[NCL-6165] pass restMode to the adjust tools

---

repour/adjust/adjust.py
repour/adjust/scala_provider.py

[NCL-6339] add support for smeg, scala alignment tool

---

repour/adjust/adjust.py

[NCL-6339] fix sbt alignment

---

repour/adjust/scala_provider.py

fix sbt alignment once again

---

repour/adjust/scala_provider.py

remove misleading log

---

repour/adjust/scala_provider.py

remove forgotten misleading log

---

pyproject.toml
repour/adjust/util.py
repour/lib/logs/file_callback_log.py
repour/lib/logs/log_util.py
repour/main.py
repour/server/endpoint/endpoint.py
repour/server/endpoint/ws.py

Upgrade to Python 3.8

---

test/util.py

Cleanup of tests

---

poetry.lock
pyproject.toml

Update cryptography version to latest

---

repour/lib/logs/file_callback_log.py
repour/main.py

Bug fix for filecallback.py on Python 3.8

---

.github/dependabot.yml

This reverts commit 026dba1f3feee8dbb2f3522d0d27c5d4dc41ea6c.

Revert "Remove dependabot.yaml file"

---

README.asciidoc
repour/adjust/adjust.py
repour/adjust/util.py
repour/config/default-config.json
repour/server/endpoint/validation.py

[NCL-6905] Update Repour for prefer_prod build aligment option

---

repour/lib/scm/asgit.py
repour/lib/scm/git.py

[NCLSUP-507] Disable more tryAtomic

---

repour/main.py

[NCL-6564] Remove unecessary log context

---

repour/__main__.py
repour/adjust/adjust.py
repour/adjust/gradle_provider.py
repour/adjust/pme_provider.py
repour/adjust/process_provider.py
repour/adjust/project_manipulator_provider.py
repour/adjust/scala_provider.py
repour/adjust/util.py
repour/asutil.py
repour/auth/auth.py
repour/clone.py
repour/main.py
repour/repo.py
repour/server/endpoint/endpoint.py
repour/server/endpoint/external_to_internal.py
repour/server/endpoint/info.py
repour/server/endpoint/internal_scm.py
repour/server/endpoint/validation.py
repour/server/endpoint/ws.py
repour/server/server.py

- It's much easier to understand
- Tells you exactly what is imported
- PEP8 recommends it and our layout isn't that crazy

Use absolute imports instead of relatives

---

repour/server/endpoint/endpoint.py

Fix error in absolute import

---

script/download-project-manipulator.sh

[2.3] Add download-project-manipulator.sh for snapshot and latest

---

script/download-project-manipulator.sh

Add download-project-manipulator.sh for snapshot and latest

---

.pre-commit-config.yaml
repour/adjust/adjust.py
repour/adjust/gradle_provider.py
repour/adjust/scala_provider.py
repour/adjust/util.py
repour/asutil.py
repour/clone.py
repour/server/endpoint/cancel.py
repour/server/endpoint/endpoint.py
repour/server/endpoint/external_to_internal.py
repour/server/endpoint/validation.py
repour/server/endpoint/ws.py
repour/websockets.py

Update to latest black version for code formatting

---

repour/server/endpoint/external_to_internal.py
test/test_external_to_internal.py

[NCL-7055] Handle external git url with trailing slash

---

.pre-commit-config.yaml
repour/adjust/adjust.py
repour/adjust/gradle_provider.py
repour/adjust/scala_provider.py
repour/adjust/util.py
repour/asutil.py
repour/clone.py
repour/server/endpoint/cancel.py
repour/server/endpoint/endpoint.py
repour/server/endpoint/external_to_internal.py
repour/server/endpoint/validation.py
repour/server/endpoint/ws.py
repour/websockets.py
test/test_external_to_internal.py

V2.3 various fixes

---

repour/lib/scm/asgit.py

[NCLSUP-666] Only push the created tag after alignment

---

repour/lib/scm/asgit.py

[v2.3][NCLSUP-666] Only push the created tag after alignment

---

repour/adjust/gradle_provider.py
repour/adjust/pme_provider.py

[NCL-7083] Apply the version suffix alt only if suffix specified

---

repour/adjust/adjust.py
repour/server/endpoint/endpoint.py

[NCL-7133] Change Repour to use more specific user logs

---

repour/adjust/adjust.py
repour/server/endpoint/endpoint.py

[v2.3][NCL-7133] Change Repour to use more specific user logs

---

poetry.lock
pyproject.toml
repour/main.py

Make repour stdout log print in JSON

---

repour/main.py

[NCL-7150] change "levelName" to "level" for kafka

---

repour/lib/logs/json_custom_formatter.py
repour/main.py

[NCL-7150] Also customize the json stdout

---

README.asciidoc
repour/main.py

[NCL-7142] Add support for kafka auth using SASL

---

README.asciidoc
repour/main.py

[v2.3][NCL-7142] Add support for kafka auth using SASL

---

repour/main.py

max timeout kafka value has to be an int

---

repour/asutil.py
repour/lib/scm/git.py

[NCL-7232] Ignore stderr log for git show-branch and git tag commands

---

repour/adjust/process_provider.py

[NCL-7263] Fix path to grab results

---

repour/server/server.py

[NCL-7312] Log events of interest

---

repour/lib/scm/git.py

[NCLSUP-750] Fetch tags with also '--all' option

---

poetry.lock
pyproject.toml

[NCL-7340] Add OTEL auto instrumentation libraries

---

poetry.lock
pyproject.toml
repour/adjust/util.py
repour/main.py
repour/server/endpoint/endpoint.py

NCL-7340 - Add integration wirth logging; read and set otel information via http-headers

---

repour/main.py

Remove otelSpanID and otelTraceID in log

---

repour/adjust/adjust.py
repour/lib/scm/git.py

[NCLSUP-788] Print commit id of synced repo

---

repour/adjust/adjust.py

[NCLSUP-788] Fix logger format

---

repour/adjust/util.py

[NCL-7340] Fix typos in mdc values

---

poetry.lock
pyproject.toml

[NCL-7340] - Add instrumentation of aiohttpclient

---

repour/server/endpoint/endpoint.py

trace-id -> trace_id
span-id -> span_id

[NCL-7340] Change http headers for opentelemetry

---

repour/server/endpoint/endpoint.py

[NCL-7340] Properly generate a span for opentelemetry

---

poetry.lock
pyproject.toml
repour/adjust/adjust.py
repour/adjust/util.py
repour/lib/logs/log_util.py
repour/server/endpoint/endpoint.py

Expose traceparent variable

---

repour/adjust/adjust.py

https://opentelemetry-python.readthedocs.io/en/latest/api/trace.span.html#opentelemetry.trace.span.TraceFlags

traceflags is based on an int and not iterable

---

repour/adjust/adjust.py
repour/asutil.py

Consider repour's env vars in the alignment process

---

repour/adjust/adjust.py

Fix the generation of the traceparent

---

pyproject.toml

Add allowed_externals to adapt to tox 4

---

repour/adjust/adjust.py
repour/lib/scm/git.py

[v2.4][NCLSUP-788] Print commit id of synced repo

---

repour/lib/scm/asgit.py
repour/lib/scm/git.py

[v2.4][NCLSUP-830] Detect tag collision and fail

---

script/download-pme.sh

add option to override PME snapshot in repour

---

repour/adjust/process_provider.py

Revert unnecessary escaping

---

README.asciidoc
repour/main.py

[NCL-7407] Add ability to configure sasl mechanism

---

README.asciidoc
repour/main.py

[v2.4][NCL-7407] Add ability to configure sasl mechanism

---

repour/server/endpoint/info.py
repour/server/server.py

[NCL-6708] Add /version endpoint

---

repour/server/endpoint/endpoint.py

[NCL-7979] Stop sending Repour logs

---

repour/auth/auth.py

Don't require auth for version endpoint

---

repour/server/endpoint/endpoint.py
repour/server/endpoint/validation.py

Add support for Rex's callback DTO

---

repour/auth/auth.py
repour/auth/oauth2_jwt.py
repour/config/default-config.json

[NCL-8049] Allow users with certain realm roles only

---

README.asciidoc
repour/auth/auth.py
repour/auth/auth_client.py
repour/config/default-config.json
repour/server/endpoint/endpoint.py

[NCL-8049] Add support for service account in callback

---

repour/adjust/adjust.py
repour/adjust/scala_provider.py
repour/adjust/util.py

Add OTEL to scala provider.

---

repour/adjust/pme_provider.py

Pass OTEL values to pme as subprocess ENV variables.

---

repour/adjust/adjust.py

[NCL-6947] Specify upstream ref commit id and if present in upstream

---

repour/auth/auth.py

Throw 401 if no auth token present

---

repour/adjust/adjust.py
repour/adjust/pme_provider.py
repour/adjust/scala_provider.py
repour/adjust/util.py
repour/asutil.py
repour/auth/auth.py
repour/config/default-config.json
repour/server/endpoint/info.py
repour/server/server.py

Backport from main

---

README.asciidoc
repour/auth/auth.py
repour/auth/auth_client.py
repour/auth/oauth2_jwt.py
repour/config/default-config.json
repour/server/endpoint/endpoint.py

[NCL-8232] PNC 2.6 backport

---

poetry.lock
pyproject.toml

Reverts project-ncl/repour#621

Revert "Bump setuptools from 69.0.0 to 69.0.2"

---

repour/server/endpoint/internal_scm.py
repour/server/endpoint/internal_scm_gerrit.py
repour/server/endpoint/internal_scm_gitlab.py
repour/server/endpoint/validation.py
repour/server/server.py
test/test_internal_scm.py

[NCL-8044] Add git backend switching

---

repour/config/default-config.json
repour/server/endpoint/internal_scm_gitlab.py

[NCL-8044] strip the gitlab token from any newline

---

repour/server/endpoint/info.py

Thanks to @pkorytar for pointing this out!

[NCL-6708] Add CORS headers

---

repour/server/endpoint/info.py

Thanks to @pkorytar for pointing this out!

[v2.6][NCL-6708] Add CORS headers

---

repour/config/default-config.json
repour/server/endpoint/external_to_internal.py
repour/server/endpoint/internal_scm_gitlab.py
test/test_external_to_internal.py

[NCL-8044] Fix internal scm url handling issues

---

repour/server/endpoint/internal_scm_gitlab.py

+ Fix listing of subgroups when searching for an existing one
+ Fix error handling when the group already exists.
+ Fix name of local variable to not clash with the package name

[NCL-8044] Add forgotten param in GitLab subgroup create

---

repour/clone.py
repour/config/default-config.json
repour/server/endpoint/validation.py

[NCL-8044] Gitlab-related fixes

---

repour/adjust/pme_provider.py

[NCL-8369] Prevent Got PME result log to be printed twice

---

repour/server/endpoint/validation.py

[NCL-8384] Fix adjust validation to support SCP-like readwrite url

---

repour/adjust/adjust.py
repour/asutil.py
repour/config/default-config.json
repour/lib/scm/asgit.py
repour/lib/scm/gitlab.py
repour/server/endpoint/internal_scm_gitlab.py

[NCL-8253] Protect all tags for existing builds

---

repour/asutil.py
repour/lib/scm/asgit.py
repour/server/endpoint/internal_scm_gitlab.py

Fix missing param and minor string syntax + a few deprecation warnings

---

repour/adjust/adjust.py
repour/server/endpoint/internal_scm_gitlab.py

[NCL-8253] Fix project loading when url contains .git suffix

---

repour/adjust/adjust.py

[NCL-8253] Fix a typo

---

repour/lib/bifrost/client.py
repour/server/endpoint/endpoint.py

[NCL-8471] Saving progress

---

repour/lib/bifrost/client.py
repour/server/endpoint/endpoint.py

[NCL-8471] Fix bugs with bifrost implementation

---

repour/lib/bifrost/client.py

[NCL-8471] Add log information when bifrost client retries

---

repour/server/endpoint/endpoint.py

Standardize on alignment-log for the tag for bifrost

---

repour/lib/bifrost/client.py

Compress the request to upload logs to bifrost

---

repour/server/endpoint/info.py

Fix typo on git_sha

---

repour/lib/scm/git.py
repour/server/endpoint/info.py

[v2.7] Bug fixes I forgot to include

---

repour/lib/bifrost/client.py

Update final log upload endpoint

---

repour/server/endpoint/endpoint.py

Print stacktrace of exception for callback error

---

repour/server/endpoint/internal_scm_gitlab.py

[NCL-8676] Allow developers to create new tags when protecting them

---

repour/server/endpoint/internal_scm_gitlab.py

[pnc 2.7.x][NCL-8676] Allow developers to create new tags when protecting them

---

test/test_adjust.py
test/test_asgit.py
test/util.py

Now the default branch is main

Fix failing tests due to different default branch

---

repour/lib/scm/gitlab.py

[NCL-8683] Do not set default branch protection for group

---

repour/lib/scm/asgit.py
repour/lib/scm/git.py

[NCLSUP-1073] Create branch for each tag

---

repour/lib/scm/asgit.py

[NCLSUP-1073] Fix log msg

---

repour/lib/scm/asgit.py
repour/lib/scm/git.py

[v2.7][NCLSUP-1073] Create branch for each tag

---

repour/server/endpoint/endpoint.py
repour/server/server.py

[NCL-8735]: Do not send logs to bifrost when creating new SCM

---

repour/adjust/adjust.py
repour/lib/scm/git.py

[NCL-8810] use shallow clone for internal adjusts

---

repour/server/endpoint/internal_scm_gitlab.py

[NCL-8900] Fix existing repository lookup when creating a new one

---

poetry.lock

Update version lock file

---

repour/adjust/adjust.py

[NCLSUP-1166] Run the sleep only when delay greater than 0

---

repour/server/endpoint/internal_scm_gitlab.py
test/test_internal_scm_gitlab.py

[NCLSUP-1136] Add pnc to the beginning or end if begin or end with '-'

---

repour/lib/scm/git.py
test/test_git.py

[NCLSUP-1239] Add git lfs support

---

repour/adjust/adjust.py
repour/clone.py

[NCLSUP-1239] Activate git lfs if used
